# Use Node.js base image for Playwright
FROM node:18-slim

WORKDIR /usr/src/app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install all dependencies, including @faker-js/faker
RUN npm install

# Install Playwright and its dependencies
RUN npx playwright install --with-deps

# Copy your Playwright tests into the container
COPY . .

# Run the tests
CMD ["sh", "-c", "cd tests && npx playwright test"]
